"""Clean Meshy's painted crease artifacts while retaining the beak and eyes.

The original GLB is kept in ArtSource/Meshy/raw. This edits only the game's
flamingo atlas and its normals; geometry, UVs, and glossy PBR factors remain.
"""
import json
import struct
import sys
from collections import deque
from io import BytesIO
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / 'Assets/_Game/Art/Meshy/flamingo.glb'
PREVIEW = ROOT / 'Screenshots/Review/Flamingo/clean-atlas-preview.jpg'


def components(mask):
    h, w = mask.shape
    seen = np.zeros_like(mask)
    found = []
    for y, x in zip(*np.where(mask)):
        if seen[y, x]:
            continue
        q = deque([(int(y), int(x))]); seen[y, x] = True
        pixels = []
        while q:
            cy, cx = q.popleft(); pixels.append((cy, cx))
            for ny, nx in ((cy - 1, cx), (cy + 1, cx), (cy, cx - 1), (cy, cx + 1)):
                if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and not seen[ny, nx]:
                    seen[ny, nx] = True; q.append((ny, nx))
        found.append(pixels)
    return found


def cleaned_atlas(source):
    picture = Image.open(BytesIO(source)).convert('RGB')
    rgb = np.asarray(picture, dtype=np.uint8)
    small = np.asarray(picture.resize((512, 512), Image.Resampling.BILINEAR))
    # The beak is the only large nearly-black island in the atlas. Isolated
    # dark crease strokes in the pink paint do not survive this component test.
    dark = np.max(small, axis=2) < 83
    selected = np.zeros((512, 512), dtype=np.uint8)
    areas = []
    for pixels in components(dark):
        if len(pixels) >= 180:
            areas.append(len(pixels))
            for y, x in pixels:
                selected[y, x] = 255
    selected = np.asarray(Image.fromarray(selected).resize(picture.size, Image.Resampling.NEAREST)) > 0
    r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
    yellow = (r > 145) & (g > 105) & (b < 155) & (r > b * 1.4) & (g > b * 1.25)
    white = (r > 175) & (g > 165) & (b > 155) & ((r.astype(int) - b.astype(int)) < 45)
    # Small dark pupils and their white rims remain where they touch white.
    eye_near = np.asarray(Image.fromarray((white * 255).astype('uint8')).filter(ImageFilter.MaxFilter(21))) > 0
    pupils = (np.max(rgb, axis=2) < 110) & eye_near
    protected = selected | yellow | white | pupils
    # Two pixels of source paint at each beak/eye edge soften the transition.
    protected = np.asarray(Image.fromarray((protected * 255).astype('uint8')).filter(ImageFilter.MaxFilter(5))) > 0
    output = np.empty_like(rgb)
    output[:] = (255, 128, 169)
    output[protected] = rgb[protected]
    result = Image.fromarray(output)
    result.save(PREVIEW, quality=96, subsampling=0)
    print('beak components', sorted(areas, reverse=True)[:10], 'preserved pixels', int(protected.sum()), flush=True)
    data = BytesIO(); result.save(data, format='JPEG', quality=96, subsampling=0)
    return data.getvalue()


def main():
    raw = PATH.read_bytes()
    assert raw[:4] == b'glTF' and struct.unpack_from('<I', raw, 8)[0] == len(raw)
    json_size = struct.unpack_from('<I', raw, 12)[0]
    doc = json.loads(raw[20:20 + json_size])
    bin_start = 20 + json_size
    bin_size, bin_kind = struct.unpack_from('<I4s', raw, bin_start)
    assert bin_kind == b'BIN\0'
    binary = bytearray(raw[bin_start + 8:bin_start + 8 + bin_size])
    material = doc['materials'][0]
    texture = doc['textures'][material['pbrMetallicRoughness']['baseColorTexture']['index']]
    image = doc['images'][texture['source']]
    view_number = image['bufferView']
    view = doc['bufferViews'][view_number]
    start, old_len = view.get('byteOffset', 0), view['byteLength']
    jpg = cleaned_atlas(binary[start:start + old_len])
    if '--apply' not in sys.argv:
        print('Preview only:', PREVIEW)
        return
    pad = b'\0' * (-len(jpg) % 4)
    binary[start:start + old_len] = jpg + pad
    delta = len(jpg) + len(pad) - old_len
    view['byteLength'] = len(jpg)
    for other in doc['bufferViews']:
        if other is not view and other.get('byteOffset', 0) > start:
            other['byteOffset'] += delta
    doc['buffers'][0]['byteLength'] = len(binary)
    # Meshy's normal map has painted dents matching the removed atlas creases.
    # The smooth vinyl sheen is generated by interpolated mesh normals instead.
    material['normalTexture']['scale'] = 0.0
    payload = json.dumps(doc, separators=(',', ':')).encode()
    payload += b' ' * (-len(payload) % 4)
    result = struct.pack('<4sII', b'glTF', 2, 12 + 8 + len(payload) + 8 + len(binary))
    result += struct.pack('<I4s', len(payload), b'JSON') + payload
    result += struct.pack('<I4s', len(binary), b'BIN\0') + binary
    PATH.write_bytes(result)
    print('Applied cleaned atlas, no geometry or UV changes; size', len(result))


if __name__ == '__main__':
    main()
